#!/bin/bash
#
# remwsgwyd        Startup script for remwsgwyd.
# Author:          Luca Paganotti <luca.paganotti@gmail.com>
#
# chkconfig: 345 20 80
# description: Remwsgwyd is the TCP gateway interface between Arpa Lombardia \
# unix servers in use to meteorological unit and the WCF service remws.
### BEGIN INIT INFO
# Provides: $remwsgwyd
# Required-Start: $network $local_fs $syslog
# Required-Stop: 
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Enhanced eiffel system to query remws web service
# Description: Remwsgwyd is the TCP gateway interface between Arpa Lombardia 
#              unix servers in use to the meteorological unit and the WCF
#              service remws.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

RETVAL=0
PIDFILE=/var/run/remwsgwyd.pid

prog=remwsgwyd
exec=/sbin/remwsgwyd
description="TCP remws gateway"
lockfile=/var/lock/subsys/$prog
unlog_remwsgwyd=/sbin/unlogremws

# pull in sysconfig settings
[ -f /etc/sysconfig/remwsgwyd ] && . /etc/sysconfig/remwsgwyd

start() {
	[ -x $exec ] || exit 5

	#umask 077

        echo -n $"Starting $description: "
        #daemon --pidfile="$PIDFILE" $exec -i "$PIDFILE" $REMWSGWYD_OPTIONS > /dev/null 2>&1 &
        daemon --user=root $exec $REMWSGWYD_OPTIONS > /dev/null 2>&1 &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $lockfile && success && echo
        return $RETVAL
}
stop() {
        echo -n $"Shutting down $description: "
        #killproc -p "$PIDFILE" $exec
        killall -9 $exec
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $lockfile && success && echo
	RETVAL=$?
        return $RETVAL
}
remwsgwystatus() {
        status -p "$PIDFILE" -l $prog $exec
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        exit 3
        ;;
  force-reload)
        restart
        ;;
  status)
        remwsgwystatus
        ;;
  condrestart|try-restart)
        remwsgwystatus >/dev/null 2>&1 || exit 0
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
        exit 3
esac

exit $?
