'\" t
.\"     Title: nmarzi
.\"    Author: Luca Paganotti <luca.paganotti@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: November 2017
.\"    Manual: \ \&
.\"    Source: \ \& 1.0
.\"  Language: English
.\"
.TH "NMARZI" "1" "November 2017" "\ \& 1\&.0" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nmarzi \- nmarzi simulator
.SH "SYNOPSIS"
.sp
\fBnmarzi\fR
.SH "DESCRIPTION"
.sp
The nmarzi eiffel application clones the old nmarzi windows application\&.
.SH "REMARKS"
.sp
nmarzi reads \fInmarzi\&.preferences\&.xml\fR file in the home user folder\&.
.SH "EXAMPLE"
.PP
nmarzi
.RS 4
Does it\&.
.RE
.SH "AUTHOR"
.sp
nmarzi was originally written by Luca Paganotti <luca\&.paganotti@gmail\&.com>\&.
.SH "RESOURCES"
.sp
github: http://https://github\&.com/lucapaganotti/
.SH "SEE ALSO"
.sp
rt10(1), unlogremws(1), remwsgwyd(1)
.SH "COPYING"
.sp
Copyright (C) 2016\-2018 ARPA Lombardia, Luca Paganotti\&. Free use of this software is granted under the terms of the GNU General Public License (GPL), v2\&.
.SH "AUTHOR"
.PP
\fBLuca Paganotti\fR <\&luca\&.paganotti@gmail\&.com\&>
.RS 4
Author.
.RE
